### ISSUE TITLE
Cannot edit main page

### ISSUE THREAD

**Issue by madewild** [ec-doris/linkedopendata.eu#1]
https://linkedopendata.eu/w/index.php?title=Main_Page&action=edit
Wikibase error: "wikitext" content is not allowed on page Main Page in slot "Main"

maybe related to https://phabricator.wikimedia.org/T219450

**Comment by madewild** [comment]
fix: redeploy wikibase with working sparql endpoint

**Comment by D063520** [comment]
This errors is due moving the Q ids to the main space!

**Comment by madewild** [comment]
Aha you convinced me then, let's un-customise it. ;)

**Comment by madewild** [comment]
When do you think you can put the new wikibase in production?

**Comment by D063520** [comment]
Hi Max, I'm really working hard on this! Yesterday a bug took me the whole day. The reason was that I incresed the limits for the string length. Now another bug appeared. I will try my best!

**Comment by madewild** [comment]
OK no problem, I was thinking it was already working in dev. Take your time :)

**Comment by D063520** [comment]
Solved
